/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Decoder4 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel
);
    assign out_0 = (sel == 4'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 4'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 4'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 4'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 4'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 4'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 4'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 4'h7)? 1'b1 : 1'b0;
    assign out_8 = (sel == 4'h8)? 1'b1 : 1'b0;
    assign out_9 = (sel == 4'h9)? 1'b1 : 1'b0;
    assign out_10 = (sel == 4'ha)? 1'b1 : 1'b0;
    assign out_11 = (sel == 4'hb)? 1'b1 : 1'b0;
    assign out_12 = (sel == 4'hc)? 1'b1 : 1'b0;
    assign out_13 = (sel == 4'hd)? 1'b1 : 1'b0;
    assign out_14 = (sel == 4'he)? 1'b1 : 1'b0;
    assign out_15 = (sel == 4'hf)? 1'b1 : 1'b0;
endmodule


module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module counter_10 (
  input UP,
  input DOWN,
  input CLK,
  output [3:0] CNT
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire [3:0] CNT_temp;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire [1:0] s29;
  wire s30;
  wire s31;
  wire s32;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( UP ),
    .C( CLK ),
    .Q( s25 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( DOWN ),
    .C( CLK ),
    .Q( s27 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s25 ),
    .C( CLK ),
    .\~Q ( s26 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s27 ),
    .C( CLK ),
    .\~Q ( s28 )
  );
  assign s12 = (s26 & s25);
  assign s24 = (s27 & s28);
  assign s16 = (s12 ^ s24);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s0 ),
    .C( CLK ),
    .Q( s1 ),
    .\~Q ( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s3 ),
    .C( CLK ),
    .Q( s4 ),
    .\~Q ( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s6 ),
    .C( CLK ),
    .Q( s7 ),
    .\~Q ( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s9 ),
    .C( CLK ),
    .Q( s10 ),
    .\~Q ( s11 )
  );
  Mux_2x1 Mux_2x1_i8 (
    .sel( s12 ),
    .in_0( s2 ),
    .in_1( s1 ),
    .out( s13 )
  );
  Mux_2x1 Mux_2x1_i9 (
    .sel( s12 ),
    .in_0( s5 ),
    .in_1( s4 ),
    .out( s14 )
  );
  Mux_2x1 Mux_2x1_i10 (
    .sel( s12 ),
    .in_0( s8 ),
    .in_1( s7 ),
    .out( s15 )
  );
  assign s17 = (s13 & s16);
  Mux_2x1 Mux_2x1_i11 (
    .sel( s16 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .out( s20 )
  );
  assign s29[0] = (s24 & s30);
  assign s29[1] = s32;
  assign s18 = (s14 & s17);
  assign CNT_temp[0] = s1;
  assign CNT_temp[1] = s4;
  assign CNT_temp[2] = s7;
  assign CNT_temp[3] = s10;
  Mux_2x1 Mux_2x1_i12 (
    .sel( s17 ),
    .in_0( s4 ),
    .in_1( s5 ),
    .out( s21 )
  );
  assign s19 = (s15 & s18);
  Mux_2x1 Mux_2x1_i13 (
    .sel( s18 ),
    .in_0( s7 ),
    .in_1( s8 ),
    .out( s22 )
  );
  Decoder4 Decoder4_i14 (
    .sel( CNT_temp ),
    .out_0( s30 ),
    .out_10( s32 ),
    .out_15( s31 )
  );
  Mux_2x1 Mux_2x1_i15 (
    .sel( s19 ),
    .in_0( s10 ),
    .in_1( s11 ),
    .out( s23 )
  );
  Mux_4x1 Mux_4x1_i16 (
    .sel( s29 ),
    .in_0( s22 ),
    .in_1( s31 ),
    .in_2( s31 ),
    .in_3( s31 ),
    .out( s6 )
  );
  Mux_4x1 Mux_4x1_i17 (
    .sel( s29 ),
    .in_0( s21 ),
    .in_1( s31 ),
    .in_2( s31 ),
    .in_3( s31 ),
    .out( s3 )
  );
  Mux_4x1 Mux_4x1_i18 (
    .sel( s29 ),
    .in_0( s20 ),
    .in_1( s30 ),
    .in_2( s31 ),
    .in_3( s31 ),
    .out( s0 )
  );
  Mux_4x1 Mux_4x1_i19 (
    .sel( s29 ),
    .in_0( s23 ),
    .in_1( s30 ),
    .in_2( s31 ),
    .in_3( s31 ),
    .out( s9 )
  );
  assign CNT = CNT_temp;
endmodule

module counter_6 (
  input UP,
  input DOWN,
  input CLK,
  output [3:0] CNT
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire [3:0] CNT_temp;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire [1:0] s29;
  wire s30;
  wire s31;
  wire s32;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( UP ),
    .C( CLK ),
    .Q( s25 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( DOWN ),
    .C( CLK ),
    .Q( s27 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s25 ),
    .C( CLK ),
    .\~Q ( s26 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s27 ),
    .C( CLK ),
    .\~Q ( s28 )
  );
  assign s12 = (s26 & s25);
  assign s24 = (s27 & s28);
  assign s16 = (s12 ^ s24);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s0 ),
    .C( CLK ),
    .Q( s1 ),
    .\~Q ( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s3 ),
    .C( CLK ),
    .Q( s4 ),
    .\~Q ( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s6 ),
    .C( CLK ),
    .Q( s7 ),
    .\~Q ( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s9 ),
    .C( CLK ),
    .Q( s10 ),
    .\~Q ( s11 )
  );
  Mux_2x1 Mux_2x1_i8 (
    .sel( s12 ),
    .in_0( s2 ),
    .in_1( s1 ),
    .out( s13 )
  );
  Mux_2x1 Mux_2x1_i9 (
    .sel( s12 ),
    .in_0( s5 ),
    .in_1( s4 ),
    .out( s14 )
  );
  Mux_2x1 Mux_2x1_i10 (
    .sel( s12 ),
    .in_0( s8 ),
    .in_1( s7 ),
    .out( s15 )
  );
  assign s17 = (s13 & s16);
  Mux_2x1 Mux_2x1_i11 (
    .sel( s16 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .out( s20 )
  );
  assign s29[0] = (s24 & s31);
  assign s29[1] = s32;
  assign s18 = (s14 & s17);
  assign CNT_temp[0] = s1;
  assign CNT_temp[1] = s4;
  assign CNT_temp[2] = s7;
  assign CNT_temp[3] = s10;
  Mux_2x1 Mux_2x1_i12 (
    .sel( s17 ),
    .in_0( s4 ),
    .in_1( s5 ),
    .out( s21 )
  );
  assign s19 = (s15 & s18);
  Mux_2x1 Mux_2x1_i13 (
    .sel( s18 ),
    .in_0( s7 ),
    .in_1( s8 ),
    .out( s22 )
  );
  Decoder4 Decoder4_i14 (
    .sel( CNT_temp ),
    .out_0( s31 ),
    .out_6( s32 ),
    .out_15( s30 )
  );
  Mux_2x1 Mux_2x1_i15 (
    .sel( s19 ),
    .in_0( s10 ),
    .in_1( s11 ),
    .out( s23 )
  );
  Mux_4x1 Mux_4x1_i16 (
    .sel( s29 ),
    .in_0( s22 ),
    .in_1( s31 ),
    .in_2( s30 ),
    .in_3( s30 ),
    .out( s6 )
  );
  Mux_4x1 Mux_4x1_i17 (
    .sel( s29 ),
    .in_0( s21 ),
    .in_1( s30 ),
    .in_2( s30 ),
    .in_3( s30 ),
    .out( s3 )
  );
  Mux_4x1 Mux_4x1_i18 (
    .sel( s29 ),
    .in_0( s20 ),
    .in_1( s31 ),
    .in_2( s30 ),
    .in_3( s30 ),
    .out( s0 )
  );
  Mux_4x1 Mux_4x1_i19 (
    .sel( s29 ),
    .in_0( s23 ),
    .in_1( s30 ),
    .in_2( s30 ),
    .in_3( s30 ),
    .out( s9 )
  );
  assign CNT = CNT_temp;
endmodule

module D_reset (
  input CLK,
  input D,
  input RST,
  output Q,
  output \Q' 
);
  wire s0;
  wire s1;
  assign s1 = ~ RST;
  Mux_2x1 Mux_2x1_i0 (
    .sel( RST ),
    .in_0( D ),
    .in_1( s1 ),
    .out( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s0 ),
    .C( CLK ),
    .Q( Q ),
    .\~Q ( \Q'  )
  );
endmodule

module labtimer (
  input clk,
  input SW,
  input B3,
  input B2,
  input B1,
  input B0,
  input hz1,
  output [3:0] M10,
  output [3:0] M1,
  output [3:0] S10,
  output [3:0] S1
);
  wire [3:0] M10_temp;
  wire [3:0] M1_temp;
  wire [3:0] S10_temp;
  wire [3:0] S1_temp;
  wire s0;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire [3:0] s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  assign s2 = ~ SW;
  assign s34 = (SW & ~ B3);
  assign s30 = (SW & ~ B2);
  assign s27 = (SW & ~ B1);
  assign s23 = (SW & ~ B0);
  assign s3 = (hz1 & s0 & s2);
  assign s5 = (s0 & s2 & s4);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( s8 ),
    .C( hz1 ),
    .Q( s9 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s11 ),
    .C( hz1 ),
    .Q( s13 )
  );
  assign s15 = (s4 & s14 & s0 & s2);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s16 ),
    .C( hz1 ),
    .Q( s18 )
  );
  assign s20 = (s2 & s19 & s0 & s14 & s4);
  Mux_2x1 Mux_2x1_i3 (
    .sel( s22 ),
    .in_0( s23 ),
    .in_1( hz1 ),
    .out( s24 )
  );
  Mux_2x1 Mux_2x1_i4 (
    .sel( s22 ),
    .in_0( s27 ),
    .in_1( s28 ),
    .out( s29 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s7 ),
    .C( hz1 ),
    .Q( s28 )
  );
  Mux_2x1 Mux_2x1_i6 (
    .sel( s22 ),
    .in_0( s30 ),
    .in_1( s31 ),
    .out( s32 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s33 ),
    .C( hz1 ),
    .Q( s31 )
  );
  Mux_2x1 Mux_2x1_i8 (
    .sel( s22 ),
    .in_0( s34 ),
    .in_1( s35 ),
    .out( s36 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( s37 ),
    .C( hz1 ),
    .Q( s35 )
  );
  counter_10 counter_10_i10 (
    .UP( s36 ),
    .DOWN( s20 ),
    .CLK( clk ),
    .CNT( M10_temp )
  );
  counter_10 counter_10_i11 (
    .UP( s32 ),
    .DOWN( s15 ),
    .CLK( clk ),
    .CNT( M1_temp )
  );
  counter_10 counter_10_i12 (
    .UP( s24 ),
    .DOWN( s3 ),
    .CLK( clk ),
    .CNT( S1_temp )
  );
  counter_6 counter_6_i13 (
    .UP( s29 ),
    .DOWN( s5 ),
    .CLK( clk ),
    .CNT( S10_temp )
  );
  assign s22 = (s2 & s25);
  D_reset D_reset_i14 (
    .CLK( clk ),
    .D( s26 ),
    .RST( SW ),
    .Q( s25 ),
    .\Q' ( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i15 (
    .D( s18 ),
    .C( clk ),
    .Q( s19 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i16 (
    .D( s9 ),
    .C( clk ),
    .Q( s4 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i17 (
    .D( s13 ),
    .C( clk ),
    .Q( s14 )
  );
  Decoder4 Decoder4_i18 (
    .sel( S1_temp ),
    .out_0( s6 ),
    .out_9( s7 )
  );
  Decoder4 Decoder4_i19 (
    .sel( S10_temp ),
    .out_0( s11 ),
    .out_5( s12 )
  );
  Decoder4 Decoder4_i20 (
    .sel( M1_temp ),
    .out_0( s16 ),
    .out_9( s17 )
  );
  assign s21 = ~ (S1_temp | S10_temp | M1_temp | M10_temp);
  assign s26 = (s25 | (s21[0] & s21[1] & s21[2] & s21[3]));
  assign s8 = (s6 & s0);
  assign s33 = (s12 & s7);
  assign s37 = (s17 & s33);
  assign M10 = M10_temp;
  assign M1 = M1_temp;
  assign S10 = S10_temp;
  assign S1 = S1_temp;
endmodule
